apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  # namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/BROADCASTER_IMAGE
          imagePullPolicy: Always
          env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-secrets
                key: TELEGRAM_BOT_TOKEN
          - name: TELEGRAM_CHAT_ID
            valueFrom:
              secretKeyRef:
                name: telegram-secrets
                key: TELEGRAM_CHAT_ID
          - name: NATS_ENDPOINT
            value: "nats://nats:4222"
          - name: FORWARD_TO_EXTERNAL_SERVICE
            value: True