name: Release application

on:
  push:
    paths:
      - 'assingments/part4/exercise_407/**' 
      - '.github/workflows/pingpong.yaml'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./assingments/part4/exercise_407

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        run: |-
          docker build --tag "juanchobanano13/logoutput:$GITHUB_SHA" ./logoutput
          docker push "juanchobanano13/logoutput:$GITHUB_SHA"

          docker build --tag "juanchobanano13/pingpong:$GITHUB_SHA" ./pingpong
          docker push "juanchobanano13/pingpong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          kustomize edit set image PROJECT/LOGOUTPUT_IMAGE=juanchobanano13/logoutput:$GITHUB_SHA
          kustomize edit set image PROJECT/PINGPONG_IMAGE=juanchobanano13/pingpong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}
