apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/logoutput.yaml
  - manifests/pingpong.yaml
  - manifests/postgres.yaml
  - manifests/ingress.yaml
  - manifests/secret.yaml
images:
  - name: PROJECT/LOGOUTPUT_IMAGE
    newName: juanchobanano13/logoutput:v0.4.1
  - name: PROJECT/PINGPONG_IMAGE
    newName: juanchobanano13/pingpong:v0.4.1
