apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: dummysite-controller-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummysite-controller-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: dummysite-controller
  namespace: default
roleRef:
  kind: Role
  name: dummysite-controller-role
  apiGroup: rbac.authorization.k8s.io
