apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikipedia-app
  labels:
    app: wikipedia-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikipedia-app
  template:
    metadata:
      labels:
        app: wikipedia-app
    spec:
      initContainers:
        - name: fetch-kubernetes-page
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /usr/share/nginx/html && \
              curl https://en.wikipedia.org/wiki/Kubernetes -o /usr/share/nginx/html/index.html
          volumeMounts:
            - name: www-data
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www-data
              mountPath: /usr/share/nginx/html
        - name: random-wikipedia-fetcher
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sleep $((RANDOM % 600 + 300)); \
                curl https://en.wikipedia.org/wiki/Special:Random -o /usr/share/nginx/html/random.html; \
              done
          volumeMounts:
            - name: www-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wikipedia-app-service
spec:
  selector:
    app: wikipedia-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
