apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      # volumes:
      #   - name: shared-pv
      #     persistentVolumeClaim:
      #       claimName: sharefile-claim
      containers:
        - name: todo-app
          image: PROJECT/TODO_APP_IMAGE
          # resources:
          #   limits:
          #     cpu: "150m"
          #     memory: "100Mi"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8000"
            - name: TODOS_HOST
              value: "todo-backend-svc"
            - name: TODOS_PORT
              value: "2348"
          # volumeMounts:
          # - name: shared-pv
          #   mountPath: /usr/src/app/files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/TODO_BACKEND_IMAGE
          # resources:
          #   limits:
          #     cpu: "150m"
          #     memory: "100Mi"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8001"
            - name: DATABASE_HOST
              value: "postgres-svc"
            - name: DATABASE_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD