apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wiki-reminder
  namespace: project
spec:
  schedule: "0 * * * *" # Runs at the start of every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reminder
              image: PROJECT/REMAINDER_IMAGE
              imagePullPolicy: Always
              env:
                - name: TODOS_HOST
                  value: "todo-backend-svc"
                - name: TODOS_PORT
                  value: "2348"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: project
spec:
  schedule: "0 0 * * *"  # Run every day at midnight (00:00)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: PROJECT/BACKUP_IMAGE
            volumeMounts:
              - name: gke-service-account-key
                mountPath: /etc/gcp  # Path to mount the secret
                readOnly: true
            env:
              - name: DATABASE_HOST
                value: "postgres-svc"
              - name: DATABASE_PORT
                value: "5432"
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_DB
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: POSTGRES_USER
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_PASSWORD
              - name: BACKUP_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: backup-config
                    key: BACKUP_BUCKET
          restartPolicy: Never  # Run it only once each time it triggers
          volumes:
            - name: gke-service-account-key
              secret:
                secretName: gke-sa-key
