apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: exercises
data:
  # property-like keys; each key maps to a simple value
  message: "hello world"

  # file-like keys
  serverconfig.txt: |
    text=This text is from file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: exercises
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user