apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wiki-reminder
  namespace: project
spec:
  schedule: "0 * * * *" # Runs at the start of every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reminder
              image: PROJECT/REMAINDER_IMAGE
              imagePullPolicy: Always
              env:
                - name: TODOS_HOST
                  value: "todo-backend-svc.project"
                - name: TODOS_PORT
                  value: "2348"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
