apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-monitor
  # namespace: project
spec:
  metrics:
  - name: cpu-usage-rate-sum
    interval: 60s # Evaluate the metric every 60 seconds
    count: 5 # Perform the analysis 5 times before completing
    successCondition: "result[0] < 1000" # Set an appropriate threshold, e.g., 1000 millicores
    failureCondition: "result[0] >= 1000"
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1734-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="project"}[2m]))
