apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  # namespace: project
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: U2VjdXJlUGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-secrets
  # namespace: project
  labels:
    app: postgres
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: NzUyNDEzODUwMTpBQUc4bGlFSjdfLVNVajM5WkkwMFBiX2NzQzV5dU5CdXhpOA==
  TELEGRAM_CHAT_ID: NTI5OTAzODA1
