apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/podfordebugging.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
images:
  - name: PROJECT/LOGOUTPUT_IMAGE
    newName: juanchobanano13/logoutput:v0.3.9
  - name: PROJECT/PINGPONG_IMAGE
    newName: juanchobanano13/pingpong:v0.3.9