apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/podfordebugging.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
images:
  - name: PROJECT/LOGOUTPUT_IMAGE
    newName: gcr.io/dwk-gke-445012/dwk-logoutput:main-3d5e3a86d770011520a8366f6b21638356c9a5a0
  - name: PROJECT/PINGPONG_IMAGE
    newName: gcr.io/dwk-gke-445012/dwk-pingpong:main-3d5e3a86d770011520a8366f6b21638356c9a5a0
