apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharefile-claim # name of the volume claim, this will be used in the deployment
  namespace: PROJECT/NAMESPACE
spec:
  storageClassName: sharedfile-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi