name: Release application

on:
  push:

env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  #MY_VARIABLE: '${{ vars.MY_VARIABLE }}'
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: dwk-environments
  DEPLOYMENT: dwk-environments
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Project ID
        run: |
          if [ -z "${{ secrets.GKE_PROJECT }}" ]; then
            echo "Project ID is empty or not set!"
            exit 1
          else
            echo "Secret length: ${#GKE_PROJECT}"
          fi
        env:
          GKE_PROJECT: ${{ secrets.GKE_PROJECT }}

      - name: Check Secret Length
        run: |
          if [ -z "${{ secrets.GKE_SA_KEY }}" ]; then
            echo "Secret is empty or not set!"
            exit 1
          else
            echo "Secret length: ${#GKE_SA_KEY}"
          fi
        env:
          GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}


      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Build and publish
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$BRANCH-$GITHUB_SHA" .
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy
        run: |-
          kustomize edit set image PROJECT/IMAGE=gcr.io/$PROJECT_ID/$IMAGE:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $DEPLOYMENT
          kubectl get services -o wide